//! `THIRD-PARTY-LICENSES` is the shipped side of the ODbL attribution decision:
//! the binary embeds OpenStreetMap-derived timezone polygons (via `tzf-dist`),
//! and this file is the red flag if the generated notice is ever dropped from
//! the repo. Phase 5's release workflow must package `THIRD-PARTY-LICENSES`
//! alongside the binary; this test is the durable half of that obligation — if
//! the file is deleted, it reds here, on every gate run, before a release is
//! even staged.
//!
//! The file is generated, never hand-edited: from the repo root, run
//!
//!     cargo about generate about.hbs -o THIRD-PARTY-LICENSES
//!
//! with the committed `about.toml` + `about.hbs` as inputs.
//!
//! The other half of the obligation is the binary itself: a downloaded release
//! never carries the repo, so `the_built_binary_prints_the_credit` below
//! spawns the built binary and pins that `--version` prints the OSM/ODbL
//! credit with no terminal and no network.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::fs;
use std::path::Path;

/// The repo root; `THIRD-PARTY-LICENSES` sits there, beside `about.toml` and `about.hbs`.
fn notice_path() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("THIRD-PARTY-LICENSES")
}

#[test]
fn third_party_licenses_exists_at_the_repo_root() {
    let path = notice_path();
    assert!(path.is_file(), "{} is missing; regenerate it with `cargo about generate about.hbs -o THIRD-PARTY-LICENSES`", path.display());
}

#[test]
fn third_party_licenses_names_osm_odbl_and_tzf_dist() {
    let text = fs::read_to_string(notice_path()).unwrap();
    for needle in ["OpenStreetMap", "ODbL-1.0", "tzf-dist", "https://opendatacommons.org/licenses/odbl/1-0/"] {
        assert!(text.contains(needle), "THIRD-PARTY-LICENSES lacks '{needle}'");
    }
}

#[test]
fn third_party_licenses_links_the_odbl_text_instead_of_shipping_it() {
    // Decision 38: the full ODbL text does not ship; the file links it. If the
    // template conditional is ever removed, cargo-about pastes the canonical
    // text and the "not reproduced here" marker disappears with it.
    let text = fs::read_to_string(notice_path()).unwrap();
    assert!(text.contains("The full ODbL-1.0 text is not reproduced here; it is at"), "the ODbL section must link the text, not paste it");
}

#[test]
fn third_party_licenses_is_fresh_against_cargo_lock() {
    // The committed file is generated by `cargo about generate about.hbs -o THIRD-PARTY-LICENSES`.
    // It went stale once for 8 days (task 30 added two crates to the lock without regenerating),
    // and nothing in the suite compared it against the lock. This test regenerates to a temp file
    // and diffs, skipping when `cargo-about` is absent the same way the tool gates skip.
    let dir = std::env::temp_dir().join(format!("exportsnap-about-{}", std::process::id()));
    let _ = fs::remove_file(&dir);
    let output = std::process::Command::new("cargo")
        .args(["about", "generate", "about.hbs", "-o"])
        .arg(&dir)
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .output();
    let Ok(output) = output else {
        println!("SKIPPED: cargo-about is not usable here");
        return;
    };
    if !output.status.success() {
        println!("SKIPPED: cargo-about failed; regenerate by hand");
        return;
    }
    let fresh = fs::read_to_string(&dir).unwrap_or_default();
    let _ = fs::remove_file(&dir);
    let committed = fs::read_to_string(notice_path()).unwrap();
    assert_eq!(committed, fresh, "THIRD-PARTY-LICENSES is stale; regenerate with `cargo about generate about.hbs -o THIRD-PARTY-LICENSES`");
}

#[test]
fn the_built_binary_prints_the_credit_on_version_without_a_terminal() {
    // The durable half of task 22's verify line: a built binary prints the OSM
    // + ODbL credit without network or extra flags. `--version` is handled
    // before any terminal takeover, so this passes headless — `output()` gives
    // the child a captured stdout and no tty. The EPIPE path is exercised by
    // `tests/cli.rs::a_payload_flag_exits_zero_when_its_reader_has_left`, not here.
    let output = std::process::Command::new(env!("CARGO_BIN_EXE_exportsnap")).arg("--version").output().unwrap();
    assert!(output.status.success(), "--version must exit 0, got {:?}", output.status);
    let stdout = String::from_utf8(output.stdout).unwrap();
    for needle in ["OpenStreetMap", "ODbL-1.0", "https://opendatacommons.org/licenses/odbl/1-0/", "tzf-dist", "THIRD-PARTY-LICENSES"] {
        assert!(stdout.contains(needle), "--version stdout lacks '{needle}'");
    }
}
